esphome:
  name: uart_dietrich_calenta

esp8266:
  board: d1_mini

wifi:
  ssid: "ssid"
  password: "password"

# Enable logging
logger:
  hardware_uart: UART1

# web server
web_server:

# Enable Home Assistant API
api:

ota:
  platform: esphome

external_components:
  - source: github://kakaki/esphome_dietrich
    components: [ dietrich ]
  # or locally, when this YAML lives inside a clone of the repository:
  # - source: components

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: GPIO1
  rx_pin: GPIO3
  # stop_bits: 1

text_sensor:
  - platform: template
    id: dietrich_state_txt
    name: "Boiler state"
  - platform: template
    id: dietrich_substate_txt
    name: "Boiler sub state"

dietrich:
  uart_id: uart_bus
  update_interval: 15s
  # protocol variant for Calenta / MCX Plus / Avanta V1_P5
  variant: calenta_v1_p5

  state:
    id: dietrich_state
    on_value:
      then:
        - lambda: |-
            if (id(dietrich_state).state==0) {id(dietrich_state_txt).publish_state("0:Standby");}
            else if (id(dietrich_state).state==1) {id(dietrich_state_txt).publish_state("1:Boiler start");}
            else if (id(dietrich_state).state==2) {id(dietrich_state_txt).publish_state("2:Burner start");}
            else if (id(dietrich_state).state==3) {id(dietrich_state_txt).publish_state("3:Burning CH");}
            else if (id(dietrich_state).state==4) {id(dietrich_state_txt).publish_state("4:Burning DHW");}
            else if (id(dietrich_state).state==5) {id(dietrich_state_txt).publish_state("5:Burner stop");}
            else if (id(dietrich_state).state==6) {id(dietrich_state_txt).publish_state("6:Boiler stop");}
            else if (id(dietrich_state).state==7) {id(dietrich_state_txt).publish_state("7:-");}
            else if (id(dietrich_state).state==8) {id(dietrich_state_txt).publish_state("8:Controlled stop");}
            else if (id(dietrich_state).state==9) {id(dietrich_state_txt).publish_state("9:Blocking mode");}
            else if (id(dietrich_state).state==10) {id(dietrich_state_txt).publish_state("10:Locking mode");}
            else if (id(dietrich_state).state==11) {id(dietrich_state_txt).publish_state("11:Chimney mode L");}
            else if (id(dietrich_state).state==12) {id(dietrich_state_txt).publish_state("12:Chimney mode h");}
            else if (id(dietrich_state).state==13) {id(dietrich_state_txt).publish_state("13:Chimney mode H");}
            else if (id(dietrich_state).state==14) {id(dietrich_state_txt).publish_state("14:-");}
            else if (id(dietrich_state).state==15) {id(dietrich_state_txt).publish_state("15:Manual-heatdemand");}
            else if (id(dietrich_state).state==16) {id(dietrich_state_txt).publish_state("16:Boiler-frost-protection");}
            else if (id(dietrich_state).state==17) {id(dietrich_state_txt).publish_state("17:De-aeration");}
            else
              {id(dietrich_state_txt).publish_state("999:Unknown");}

  sub_state:
    id: dietrich_substate
    on_value:
      then:
        - lambda: |-
            if (id(dietrich_substate).state==0) {id(dietrich_substate_txt).publish_state("0:Standby");}
            else if (id(dietrich_substate).state==1) {id(dietrich_substate_txt).publish_state("1:Anti-cycling");}
            else if (id(dietrich_substate).state==2) {id(dietrich_substate_txt).publish_state("2:Open hydraulic valve");}
            else if (id(dietrich_substate).state==3) {id(dietrich_substate_txt).publish_state("3:Pump start");}
            else if (id(dietrich_substate).state==4) {id(dietrich_substate_txt).publish_state("4:Wait for burner start");}
            else if (id(dietrich_substate).state==5) {id(dietrich_substate_txt).publish_state("5:-");}
            else if (id(dietrich_substate).state==6) {id(dietrich_substate_txt).publish_state("6:-");}
            else if (id(dietrich_substate).state==7) {id(dietrich_substate_txt).publish_state("7:-");}
            else if (id(dietrich_substate).state==8) {id(dietrich_substate_txt).publish_state("8:-");}
            else if (id(dietrich_substate).state==9) {id(dietrich_substate_txt).publish_state("9:-");}
            else if (id(dietrich_substate).state==10) {id(dietrich_substate_txt).publish_state("10:Open external gas valve");}
            else if (id(dietrich_substate).state==11) {id(dietrich_substate_txt).publish_state("11:Fan to fluegasvalve speed");}
            else if (id(dietrich_substate).state==12) {id(dietrich_substate_txt).publish_state("12:Open fluegasvalve");}
            else if (id(dietrich_substate).state==13) {id(dietrich_substate_txt).publish_state("13:Pre-purge");}
            else if (id(dietrich_substate).state==14) {id(dietrich_substate_txt).publish_state("14:Wait for release");}
            else if (id(dietrich_substate).state==15) {id(dietrich_substate_txt).publish_state("15:Burner start");}
            else if (id(dietrich_substate).state==16) {id(dietrich_substate_txt).publish_state("16:VPS test");}
            else if (id(dietrich_substate).state==17) {id(dietrich_substate_txt).publish_state("17:Pre-ignition");}
            else if (id(dietrich_substate).state==18) {id(dietrich_substate_txt).publish_state("18:Ignition");}
            else if (id(dietrich_substate).state==19) {id(dietrich_substate_txt).publish_state("19:Flame check");}
            else if (id(dietrich_substate).state==20) {id(dietrich_substate_txt).publish_state("20:Interpurge");}
            else if (id(dietrich_substate).state==30) {id(dietrich_substate_txt).publish_state("30:Normal internal setpoint");}
            else if (id(dietrich_substate).state==31) {id(dietrich_substate_txt).publish_state("31:Limited internal setpoint");}
            else if (id(dietrich_substate).state==32) {id(dietrich_substate_txt).publish_state("32:Normal power control");}
            else if (id(dietrich_substate).state==33) {id(dietrich_substate_txt).publish_state("33:Gradient control level 1");}
            else if (id(dietrich_substate).state==34) {id(dietrich_substate_txt).publish_state("34:Gradient control level 2");}
            else if (id(dietrich_substate).state==35) {id(dietrich_substate_txt).publish_state("35:Gradient control level 3");}
            else if (id(dietrich_substate).state==36) {id(dietrich_substate_txt).publish_state("36:Flame protection");}
            else if (id(dietrich_substate).state==37) {id(dietrich_substate_txt).publish_state("37:Stabilisation time");}
            else if (id(dietrich_substate).state==38) {id(dietrich_substate_txt).publish_state("38:Cold start");}
            else if (id(dietrich_substate).state==39) {id(dietrich_substate_txt).publish_state("39:Limited power Tfg");}
            else if (id(dietrich_substate).state==40) {id(dietrich_substate_txt).publish_state("40:Burner stop");}
            else if (id(dietrich_substate).state==41) {id(dietrich_substate_txt).publish_state("41:Post purge");}
            else if (id(dietrich_substate).state==42) {id(dietrich_substate_txt).publish_state("42:Fan to flue gas valve speed");}
            else if (id(dietrich_substate).state==43) {id(dietrich_substate_txt).publish_state("43:Close flue gas valve");}
            else if (id(dietrich_substate).state==44) {id(dietrich_substate_txt).publish_state("44:Stop fan");}
            else if (id(dietrich_substate).state==45) {id(dietrich_substate_txt).publish_state("45:Close external gas valve");}
            else if (id(dietrich_substate).state==46) {id(dietrich_substate_txt).publish_state("46:-");}
            else if (id(dietrich_substate).state==47) {id(dietrich_substate_txt).publish_state("47:-");}
            else if (id(dietrich_substate).state==48) {id(dietrich_substate_txt).publish_state("48:-");}
            else if (id(dietrich_substate).state==49) {id(dietrich_substate_txt).publish_state("49:-");}
            else if (id(dietrich_substate).state==60) {id(dietrich_substate_txt).publish_state("60:Pump post running");}
            else if (id(dietrich_substate).state==61) {id(dietrich_substate_txt).publish_state("61:Pump stop");}
            else if (id(dietrich_substate).state==62) {id(dietrich_substate_txt).publish_state("62:Close hydraulic valve");}
            else if (id(dietrich_substate).state==63) {id(dietrich_substate_txt).publish_state("63:Start anti-cycle timer");}
            else if (id(dietrich_substate).state==255) {id(dietrich_substate_txt).publish_state("255:Reset wait time");}
            else
              {id(dietrich_substate_txt).publish_state("999:Unkown Sub-State");}

  lockout:
    name: "Boiler lockout"
  blocking:
    name: "Boiler blocking"

  flow_temp:
    name: "Boiler flow temp"
  return_temp:
    name: "Boiler return temp"
  outside_temp:
    name: "Boiler outside temp"
  calorifier_temp:
    name: "Boiler calorifier temp"
  boiler_control_temp:
    name: "Boiler control temp"
  room_temp:
    name: "Boiler room temp"
  ch_setpoint:
    name: "Boiler setpoint CH"
  dhw_setpoint:
    name: "Boiler setpoint DHW"
  room_temp_setpoint:
    name: "Boiler setpoint room"

  fan_speed_setpoint:
    name: "Boiler setpoint fanspeed"
    accuracy_decimals: 2
  fan_speed:
    name: "Boiler fanspeed"
    accuracy_decimals: 2

  ionisation_current:
    name: "Boiler ionisation_current"
    unit_of_measurement: "μA"
  internal_setpoint:
    name: "Boiler internal_setpoint"
  available_power:
    name: "Boiler available_power"
  pump_percentage:
    name: "Boiler pump_percentage"
  desired_max_power:
    name: "Boiler desired_max_power"
  actual_power:
    name: "Boiler actual_power"

  demand_source_bit0:
    name: "Boiler Mod.Controller Connected"
  demand_source_bit1:
    name: "Boiler Heat demand from Mod.Controller"
  demand_source_bit2:
    name: "Boiler Heat demand from on/off controller"
  demand_source_bit3:
    name: "Boiler Frost Protection"
  demand_source_bit4:
    name: "Boiler DHW Eco"
  demand_source_bit5:
    name: "Boiler DHW Blocking"
  demand_source_bit6:
    name: "Boiler Anti Legionella"
  demand_source_bit7:
    name: "Boiler DHW Heat Demand"

  hours_run_pump:
    name: "Boiler hours_run_pump_sensor"
  hours_run_3way:
    name: "Boiler hours_run_3way_sensor"
  hours_run_ch:
    name: "Boiler hours_run_ch_sensor"
  hours_run_dhw:
    name: "Boiler hours_run_dhw_sensor"
  power_supply_aval_hours:
    name: "Boiler power_supply_aval_hours_sensor"

  pump_starts:
    name: "Boiler pump_starts_sensor"
    unit_of_measurement: count
  number_of_3way_valve_cycles:
    name: "Boiler number_of3way_valce_cycles_sensor"
    unit_of_measurement: count
  burner_start_dhw:
    name: "Boiler burner_start_dhw_sensor"
    unit_of_measurement: count
  total_burner_start:
    name: "Boiler total_burner_start_sensor"
    unit_of_measurement: count
  failed_burner_start:
    name: "Boiler failed_burner_start_sensor"
    unit_of_measurement: count
  number_flame_loss:
    name: "Boiler number_flame_loss_sensor"

  hydro_pressure:
    name: "Boiler hydro_pressure_sensor"
  control_temp:
    name: "Boiler control_temp_sensor"
  dhw_flowrate:
    name: "Boiler dhw_flowrate_sensor"

sensor:
  - platform: wifi_signal
    name: "Boiler WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Boiler Uptime"
